title: Xinwang Liu's Homepage
author: GitHub User
description: > # this means to ignore newlines until "show_exerpts:"
  Professor with the school of computer, National 
  University of Defense Technology (NUDT), Changsha, 
  Hunan, China. My research interests include kernel 
  learning, multi-view learning, unsupervised representation 
  learning and some related topics. 
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Xiangke Wang
  tagline: Professor
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    github:  xkwang2000


    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed